FROM ghhenry/python3:1.0.0
LABEL author="Gervaise H. Henry"

RUN git clone https://github.com/GHAStVHenry/single-cell-curation.git && \
    cd single-cell-curation && \
    git checkout GHH && \
    make install